ModulosUsuario/ModulosUsuario/Models/Material.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ModulosUsuario.Models
{
    public class Material
    {
        [Key]
        public int MaterialId { get; set; }

        [Required]
        [Display(Name = "Descrição")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Nome")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Data de vencimento")]
        [DataType(DataType.Date)]
        public DateTime DueDate { get; set; }

        [Required]
        [Display(Name = "Unidade")]
        public int Unity { get; set; }

        [Required]
        public int UnityTypeId { get; set; }

        [Required]
        [Display(Name = "Preço de custo")]
        public decimal PriceCost { get; set; }

        [Required]
        public bool Active { get; set; }

        public virtual UnityType UnityType { get; set; }

        public List<MaterialTransaction> MaterialTransactions { get; set; }
    }
}

ModulosUsuario/ModulosUsuario/Controllers/MaterialController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ModulosUsuario.Interfaces.Services;
using ModulosUsuario.Models;

namespace ModulosUsuario.Controllers
{
    public class MaterialController : Controller
    {

        private readonly IMaterialService materialService;
        private readonly IUnityTypeService unityTypeService;

        public MaterialController(IMaterialService materialService,
                                 IUnityTypeService unityTypeService)
        {
            this.materialService = materialService;
            this.unityTypeService = unityTypeService;
        }

        public IActionResult Index()
        {
            var materials = materialService.GetMaterials();
            return View(materials);
        }

        [HttpPost]
        public ActionResult CreateOrEdit(Material material)
        {
            if (this.ModelState.IsValid)
            {
                material = materialService.CreateOrEditMaterial(material);
                return RedirectToAction("Index");
            }

            ViewBag.UnityTypes = new SelectList(unityTypeService.GetUnityTypes(), "UnityTypeId", "Description");

            return View("Form", material);
        }

        public ActionResult CreateOrEdit(int materialId)
        {

            var material = materialService.GetMaterialById(materialId);

            ViewBag.UnityTypes = new SelectList(unityTypeService.GetUnityTypes(), "UnityTypeId", "Description");

            return View("Form", material);
        }

        [HttpPost]
        public ActionResult Delete(int materialId)
        {
            materialService.DeleteMaterial(materialId);

            return RedirectToAction("Index");
        }

    }
}

ModulosUsuario/ModulosUsuario/Views/Material/Form.cshtml
@model ModulosUsuario.Models.Material
@{ ViewData["Title"] = Model.MaterialId == 0 ? "Criar Material" : "Editar Material"; }
@{ 
    var title = Model.MaterialId == 0 ? "Criar" : "Editar";
}
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">@title Material</h3>
    </div>

    <form asp-controller="Material" asp-action="CreateOrEdit" asp-antiforgery="true" method="post">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <h3 class="card-title">Informações do Material</h3>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        @Html.HiddenFor(h => h.MaterialId)
                        <div class="row">
                            <div class="form-group col-md-4">
                                <label asp-for="Name"></label>
                                <input asp-for="Name" class="form-control" placeholder="Informe o Nome" />
                                <span asp-validation-for="Name" class="field-validation-valid text-danger"></span>
                            </div>
                            <div class="form-group col-md-4">
                                <label asp-for="PriceCost"></label>
                                <input asp-for="PriceCost" class="form-control" placeholder="Digite o Preço de Custo" />
                                <span asp-validation-for="PriceCost" class="field-validation-valid text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-4">
                                <label asp-for="DueDate"></label>
                                <input asp-for="DueDate" class="form-control" placeholder="Informe a Data de Vencimento" />
                            </div>
                            <div class="form-group col-md-4">
                                <label asp-for="UnityType"></label>
                                @Html.DropDownList("UnityTypeId", (IEnumerable<SelectListItem>)ViewBag.UnityTypes, null, new { @class = "form-control" })
                                <span asp-validation-for="UnityTypeId" class="field-validation-valid text-danger"></span>
                            </div>
                            <div class="form-group col-md-4">
                                <label asp-for="Unity"></label>
                                <input type="number" asp-for="Unity" class="form-control" placeholder="Digite a Unidade" />
                                <span asp-validation-for="Unity" class="field-validation-valid text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-12">
                                <label asp-for="Description"></label>
                                <input asp-for="Description" class="form-control" placeholder="Informe a Descrição do Material" />
                                <span asp-validation-for="Description" class="field-validation-valid text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <div style="text-align:end">
                            <a asp-action="Index" class="btn btn-dark mr-2">Retornar</a>
                            <input type="submit" class="btn btn-success" value="Salvar" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

ModulosUsuario/ModulosUsuario/Views/Material/Index.cshtml
@model IEnumerable<Material>
@{ ViewData["Title"] = "Materiais"; }

<script src="~/js/views/material.js"></script>

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header d-inline">
                <h3 class="box-title">Gerenciar Materiais <a class="float-right" href="/Material/CreateOrEdit" role="button" title="Criar Material"><i class="fas fa-plus-square"></i></a></h3>
            </div>
            <div class="box-body">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Description)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Unity)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.DueDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PriceCost)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Unity)
                                    @Html.DisplayFor(modelItem => item.UnityType.Description)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DueDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PriceCost)
                                </td>
                                <td align="center">
                                    @Html.ActionLink("Editar", "CreateOrEdit", "Material", new { materialId = item.MaterialId }, new { @class = "btn btn-sm btn-primary" })
                                    <button deleteMaterialId="@item.MaterialId" type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#deleteModal" onclick="materialController.deleteModalId(this)">
                                        <i class="fas fa-trash-alt"></i> Deletar
                                    </button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Confirmar Deleção</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                Tem certeza que deseja deletar esse material?
            </div>
            <div class="modal-footer">
                <form action="" id="deleteModalAction" asp-antiforgery="true" method="post">
                    <input type="submit" class="btn bg-danger" value="Deletar" />
                </form>
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>