ModulosUsuario/ModulosUsuario/Models/MaterialTransaction.cs
using System.ComponentModel.DataAnnotations;

namespace ModulosUsuario.Models
{
    public class MaterialTransaction
    {
        [Key]
        public int MaterialTransactionId { get; set; }

        [Required]
        public int MaterialId { get; set; }

        [Required]
        [Display(Name = "Quantidade")]
        public int Quantity { get; set; }

        [Required]
        [Display(Name = "Valor unitário")]
        public decimal UnityValue { get; set; }

        [Required]
        public int TransactionTypeId { get; set; }

        [Required]
        public int StockId { get; set; }

        public Stock Stock { get; set; }

        public TransactionType TransactionType { get; set; }

        public Material Material { get; set; }
    }
}

ModulosUsuario/ModulosUsuario/Models/ProductTransaction.cs
using System.ComponentModel.DataAnnotations;

namespace ModulosUsuario.Models
{
    public class ProductTransaction
    {
        [Key]
        public int ProductTransactionId { get; set; }

        [Required]
        [Display(Name = "Produto")]
        public int ProductId { get; set; }

        [Required]
        [Display(Name = "Quantidade")]
        public int Quantity { get; set; }

        [Required]
        [Display(Name = "Valor unitário")]
        public decimal UnityValue { get; set; }

        [Required]
        public int TransactionTypeId { get; set; }

        [Required]
        public int StockId { get; set; }

        [Required]
        public int UserId { get; set; }

        public virtual Product Product { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual TransactionType TransactionType { get; set; }
        public virtual User User { get; set; }
        public virtual Sale Sale { get; set; }
    }
}

ModulosUsuario/ModulosUsuario/Models/ToolsTransaction.cs
using System.ComponentModel.DataAnnotations;

namespace ModulosUsuario.Models
{
    public class ToolsTransaction
    {
        [Key]
        public int ToolsTransactionId { get; set; }

        [Required]
        public int ToolId { get; set; }

        [Required]
        [Display(Name = "Quantidade")]
        public int Quantity { get; set; }

        [Required]
        [Display(Name = "Valor unitário")]
        public decimal UnityValue { get; set; }

        [Required]
        public int TransactionTypeId { get; set; }

        [Required]
        public int StockId { get; set; }

        public TransactionType TransactionType { get; set; }

        public Stock Stock { get; set; }

        public Tools Tool { get; set; }
    }
}

ModulosUsuario/ModulosUsuario/Models/TransactionType.cs
using System.ComponentModel.DataAnnotations;

namespace ModulosUsuario.Models
{
    public class TransactionType
    {
        [Key]
        public int TransactionTypeId { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public bool IsIncoming { get; set; }
    }
}

ModulosUsuario/ModulosUsuario/Models/TransactionsViewModel.cs
using System.Collections.Generic;

namespace ModulosUsuario.Models
{
    public class TransactionsViewModel
    {
        public Stock Stock { get; set; }
        public List<ProductTransaction> ProductTransactions { get; set; }
        public List<MaterialTransaction> MaterialTransactions { get; set; }
        public List<ToolsTransaction> ToolsTransactions { get; set; }
    }
}

ModulosUsuario/ModulosUsuario/Controllers/TransactionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ModulosUsuario.Interfaces.Services;
using ModulosUsuario.Models;
using Syncfusion.Pdf;
using Syncfusion.Pdf.Graphics;
using Syncfusion.Drawing;
using System.IO;

namespace ModulosUsuario.Controllers
{
    public class TransactionController : Controller
    {

        private readonly ITransactionService transactionService;
        private readonly IStockService stockService;
        private readonly IProductService productService;
        private readonly IMaterialService materialService;
        private readonly IToolsService toolsService;

        public TransactionController(ITransactionService transactionService,
            IStockService stockService, 
            IProductService productService,
            IMaterialService materialService,
            IToolsService toolsService)
        {
            this.transactionService = transactionService;
            this.stockService = stockService;
            this.productService = productService;
            this.materialService = materialService;
            this.toolsService = toolsService;
        }

        public IActionResult Index()
        {
            return View(transactionService.GetTransactionsList());
        }

        public IActionResult Details(int stockId)
        {
            return View(transactionService.GetTransactionsByStock(stockId));
        }

        [HttpPost]
        public ActionResult CreateProductTransaction(ProductTransaction productTransaction)
        {
            try
            {
                if (this.ModelState.IsValid)
                {
                    productTransaction = transactionService.CreateProductTransaction(productTransaction);
                    return RedirectToAction("Details", new { stockId = productTransaction.StockId });
                }

                ViewBag.TransactionTypes = new SelectList(transactionService.GetTransactionTypeList(), "TransactionTypeId", "Description");
                ViewBag.Products = new SelectList(productService.GetProducts(), "ProductId", "Name");

                return View("ProductTransactionForm", productTransaction);
            }
            catch (System.Exception)
            {
                return BadRequest();
            }
            
        }

        public ActionResult CreateProductTransaction(int stockId)
        {
            var productTransaction = new ProductTransaction { StockId = stockId };

            ViewBag.TransactionTypes = new SelectList(transactionService.GetTransactionTypeList(), "TransactionTypeId", "Description");
            ViewBag.Products = new SelectList(productService.GetProducts(), "ProductId", "Name");

            return View("ProductTransactionForm", productTransaction);
        }

        [HttpPost]
        public ActionResult CreateMaterialTransaction(MaterialTransaction materialTransaction)
        {
            if (this.ModelState.IsValid)
            {
                materialTransaction = transactionService.CreateMaterialTransaction(materialTransaction);
                return RedirectToAction("Details", new { stockId = materialTransaction.StockId });
            }

            ViewBag.TransactionTypes = new SelectList(transactionService.GetTransactionTypeList(), "TransactionTypeId", "Description");
            ViewBag.Materials = new SelectList(materialService.GetMaterials(), "MaterialId", "Name");

            return View("MaterialTransactionForm", materialTransaction);
        }

        public ActionResult CreateMaterialTransaction(int stockId)
        {
            var materialTransaction = new MaterialTransaction { StockId = stockId };

            ViewBag.TransactionTypes = new SelectList(transactionService.GetTransactionTypeList(), "TransactionTypeId", "Description");
            ViewBag.Materials = new SelectList(materialService.GetMaterials(), "MaterialId", "Name");

            return View("MaterialTransactionForm", materialTransaction);
        }


        [HttpPost]
        public ActionResult CreateToolTransaction(ToolsTransaction toolTransaction)
        {
            if (this.ModelState.IsValid)
            {
                toolTransaction = transactionService.CreateToolTransaction(toolTransaction);
                return RedirectToAction("Details", new { stockId = toolTransaction.StockId });
            }

            ViewBag.TransactionTypes = new SelectList(transactionService.GetTransactionTypeList(), "TransactionTypeId", "Description");
            ViewBag.Tools = new SelectList(toolsService.GetTools(), "ToolsId", "Name");

            return View("ToolTransactionForm", toolTransaction);
        }

        public ActionResult CreateToolTransaction(int stockId)
        {
            var toolTransaction = new ToolsTransaction { StockId = stockId };

            ViewBag.TransactionTypes = new SelectList(transactionService.GetTransactionTypeList(), "TransactionTypeId", "Description");
            ViewBag.Tools = new SelectList(toolsService.GetTools(), "ToolsId", "Name");

            return View("ToolTransactionForm", toolTransaction);
        }

        public ActionResult DownloadDocumentProduct(int productTransactionId)
        {
            var productTransaction = transactionService.GetProductTransaction(productTransactionId);
            var text = "IMPRESSÃO DO DOCUMENTO FISCAL\n" + "Nome da filial: " + productTransaction.Stock.Branch.Description + 
                "\nProduto: " + productTransaction.Product.Name + 
                "\nQuantidade: " + productTransaction.Quantity + 
                "\nValor unitário: " + productTransaction.UnityValue + 
                "\nValor total: " + (productTransaction.Quantity * productTransaction.UnityValue) + 
                "\n\n\nTipo da transação: " + productTransaction.TransactionType.Description;
            return CreateDocument(text);
        }
        public ActionResult DownloadDocumentTools(int toolsTransactionId)
        {
            var toolsTransaction = transactionService.GetToolTransaction(toolsTransactionId);
            var text = "IMPRESSÃO DO DOCUMENTO FISCAL\n" + "Nome da filial: " + toolsTransaction.Stock.Branch.Description +
                            "\nFerramenta: " + toolsTransaction.Tool.Name +
                            "\nQuantidade: " + toolsTransaction.Quantity +
                            "\nValor unitário: " + toolsTransaction.UnityValue +
                            "\nValor total: " + (toolsTransaction.Quantity * toolsTransaction.UnityValue) +
                            "\n\n\nTipo da transação: " + toolsTransaction.TransactionType.Description;
            return CreateDocument(text);
        }

        public ActionResult DownloadDocumentMaterial(int materialTransactionId)
        {
            var materialTransaction = transactionService.GetMaterialTransaction(materialTransactionId);
            var text = "IMPRESSÃO DO DOCUMENTO FISCAL\n" + "Nome da filial: " + materialTransaction.Stock.Branch.Description +
                            "\nMaterial: " + materialTransaction.Material.Name +
                            "\nQuantidade: " + materialTransaction.Quantity +
                            "\nValor unitário: " + materialTransaction.UnityValue +
                            "\nValor total: " + (materialTransaction.Quantity * materialTransaction.UnityValue) +
                            "\n\n\nTipo da transação: " + materialTransaction.TransactionType.Description;
            return CreateDocument(text);
        }
        private FileStreamResult CreateDocument(string text)
        {
            //Create a new PDF document
            PdfDocument document = new PdfDocument();

            //Add a page to the document
            PdfPage page = document.Pages.Add();

            //Create PDF graphics for the page
            PdfGraphics graphics = page.Graphics;

            //Set the standard font
            PdfFont font = new PdfStandardFont(PdfFontFamily.Helvetica, 20);

            //Draw the text
            graphics.DrawString(text, font, PdfBrushes.Black, new PointF(0, 0));

            //Saving the PDF to the MemoryStream
            MemoryStream stream = new MemoryStream();

            document.Save(stream);

            //Set the position as '0'.
            stream.Position = 0;

            //Download the PDF document in the browser
            FileStreamResult fileStreamResult = new FileStreamResult(stream, "application/pdf");

            fileStreamResult.FileDownloadName = "DocumentoFiscal.pdf";

            return fileStreamResult;
        }
        
    }
}

ModulosUsuario/ModulosUsuario/Views/Transaction/_Details/_MaterialTransactions.cshtml
@model TransactionsViewModel
<div class="card">
    <div class="card-header" id="headingTwo">
        <h5 class="mb-0">
            <button class="btn btn-link" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                Transações de Materiais
            </button>
            @Html.ActionLink("", "CreateMaterialTransaction", "Transaction", new { stockId = Model.Stock.StockId }, new { @class = "fas fa-plus-square float-right", title = "Nova Transação" })
        </h5>
    </div>
    <div id="collapseTwo" class="collapse show" aria-labelledby="headingTwo" data-parent="#accordion">
        <div class="card-body">
            <div class="row">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayName("Material")
                            </th>
                            <th>
                                @Html.DisplayName("Quantidade")
                            </th>
                            <th>
                                @Html.DisplayName("Valor Unitário")
                            </th>
                            <th>
                                @Html.DisplayName("Valor Total")
                            </th>
                            <th>
                                @Html.DisplayName("Transação")
                            </th>
                            <th>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.MaterialTransactions)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Material.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Quantity)
                                </td>
                                <td>
                                    R$@Html.DisplayFor(modelItem => item.UnityValue)
                                </td>
                                <td>
                                    R$@(item.UnityValue * item.Quantity)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TransactionType.Description)
                                </td>
                                <td align="center">
                                    @if ("Furto" != item.TransactionType.Description)
                                    {
                                        @Html.ActionLink("", "DownloadDocumentMaterial", "Transaction", new { materialTransactionId = item.MaterialTransactionId }, new { @class = "fas fa-file-download", title = "Download documento fiscal" })
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

ModulosUsuario/ModulosUsuario/Views/Transaction/_Details/_ProductTransactions.cshtml
@model TransactionsViewModel

<div class="card">
    <div class="card-header" id="headingOne">
        <h5 class="mb-0">
            <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Transações de Produtos
            </button>
            @Html.ActionLink("", "CreateProductTransaction", "Transaction", new { stockId = Model.Stock.StockId }, new { @class = "fas fa-plus-square float-right", title = "Nova Transação" })
        </h5>
    </div>
    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
        <div class="card-body">
            <div class="row">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayName("Produto")
                            </th>
                            <th>
                                @Html.DisplayName("Quantidade")
                            </th>
                            <th>
                                @Html.DisplayName("Valor Unitário")
                            </th>
                            <th>
                                @Html.DisplayName("Valor Total")
                            </th>
                            <th>
                                @Html.DisplayName("Transação")
                            </th>
                            <th>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.ProductTransactions)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Product.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Quantity)
                                </td>
                                <td>
                                    R$@Html.DisplayFor(modelItem => item.UnityValue)
                                </td>
                                <td>
                                    R$@(item.UnityValue * item.Quantity)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TransactionType.Description)
                                </td>
                                <td align="center">
                                    @if ("Furto" != item.TransactionType.Description)
                                    {
                                        @Html.ActionLink("", "DownloadDocumentProduct", "Transaction", new { productTransactionId = item.ProductTransactionId }, new { @class = "fas fa-file-download", title = "Download documento fiscal" })
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

ModulosUsuario/ModulosUsuario/Views/Transaction/_Details/_ToolsTransactions.cshtml
@model TransactionsViewModel
<div class="card">
    <div class="card-header" id="headingThree">
        <h5 class="mb-0">
            <button class="btn btn-link" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                Transações de Ferramentas
            </button>
            @Html.ActionLink("", "CreateToolTransaction", "Transaction", new { stockId = Model.Stock.StockId }, new { @class = "fas fa-plus-square float-right", title = "Nova Transação" })
        </h5>
    </div>
    <div id="collapseThree" class="collapse show" aria-labelledby="headingThree" data-parent="#accordion">
        <div class="card-body">
            <div class="row">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayName("Ferramenta")
                            </th>
                            <th>
                                @Html.DisplayName("Quantidade")
                            </th>
                            <th>
                                @Html.DisplayName("Valor Unitário")
                            </th>
                            <th>
                                @Html.DisplayName("Valor Total")
                            </th>
                            <th>
                                @Html.DisplayName("Transação")
                            </th>
                            <th>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.ToolsTransactions)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Tool.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Quantity)
                                </td>
                                <td>
                                    R$@Html.DisplayFor(modelItem => item.UnityValue)
                                </td>
                                <td>
                                    R$@(item.UnityValue * item.Quantity)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TransactionType.Description)
                                </td>
                                <td align="center">
                                    @if ("Furto" != item.TransactionType.Description)
                                    {
                                        @Html.ActionLink("", "DownloadDocumentTools", "Transaction", new { toolsTransactionId = item.ToolsTransactionId }, new { @class = "fas fa-file-download", title = "Download documento fiscal" })
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>