ModulosUsuario/ModulosUsuario/Models/Tools.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ModulosUsuario.Models
{
    public class Tools
    {
        [Key]
        public int ToolsId { get; set; }

        [Required]
        [Display(Name = "Nome")]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Data de Vencimento")]
        public DateTime DueDate { get; set; }

        [Required]
        [Display(Name = "Unidade")]
        public int Unity { get; set; }

        [Required]
        public int UnityTypeId { get; set; }

        [Required]
        public string Status { get; set; } // Talvez usar um Int para os Status e cada numero equivale a um status ?

        [Required]
        [Display(Name = "Preço de custo")]
        public decimal PriceCost { get; set; }

        public virtual UnityType UnityType { get; set; }

        public List<ToolsTransaction> ToolsTransactions { get; set; }

        public List<ToolsLog> ToolsLogs { get; set; }

    }
}

ModulosUsuario/ModulosUsuario/Controllers/ToolsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ModulosUsuario.Interfaces.Services;
using ModulosUsuario.Models;

namespace ModulosUsuario.Controllers
{
    public class ToolsController : Controller
    {

        private readonly IToolsService toolsService;
        private readonly IUnityTypeService unityTypeService;

        public ToolsController(IToolsService toolsService,
                                 IUnityTypeService unityTypeService)
        {
            this.toolsService = toolsService;
            this.unityTypeService = unityTypeService;
        }

        public IActionResult Index()
        {
            var toolss = toolsService.GetTools();
            return View(toolss);
        }

        [HttpPost]
        public ActionResult CreateOrEdit(Tools tools)
        {
            if (this.ModelState.IsValid)
            {
                tools = toolsService.CreateOrEditTools(tools);
                return RedirectToAction("Index");
            }

            ViewBag.UnityTypes = new SelectList(unityTypeService.GetUnityTypes(), "UnityTypeId", "Description");

            return View("Form", tools);
        }

        public ActionResult CreateOrEdit(int toolsId)
        {

            var tools = toolsService.GetToolsById(toolsId);

            ViewBag.UnityTypes = new SelectList(unityTypeService.GetUnityTypes(), "UnityTypeId", "Description");

            return View("Form", tools);
        }

        [HttpPost]
        public ActionResult Delete(int toolsId)
        {
            toolsService.DeleteTools(toolsId);

            return RedirectToAction("Index");
        }

        public ActionResult Logs(int toolsId)
        {
            return View(new Tools {ToolsId = 0});
        }

    }
}

ModulosUsuario/ModulosUsuario/Views/Tools/Form.cshtml
@model ModulosUsuario.Models.Tools
@{ ViewData["Title"] = Model.ToolsId == 0 ? "Criar Ferramenta" : "Editar Ferramenta"; }
@{
    var title = "Editar";
    if (Model.ToolsId == 0)
    {
        title = "Criar";
        Model.Status = "Novo";
    }
}
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">@title Ferramenta</h3>
    </div>

    <form asp-controller="Tools" asp-action="CreateOrEdit" asp-antiforgery="true" method="post">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <h3 class="card-title">Informações do Ferramenta</h3>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        @Html.HiddenFor(h => h.ToolsId)
                        @Html.HiddenFor(h => h.Status)
                        <div class="row">
                            <div class="form-group col-md-4">
                                <label asp-for="Name"></label>
                                <input asp-for="Name" class="form-control" placeholder="Informe o Nome" />
                                <span asp-validation-for="Name" class="field-validation-valid text-danger"></span>
                            </div>
                            <div class="form-group col-md-4">
                                <label asp-for="PriceCost"></label>
                                <input asp-for="PriceCost" class="form-control" placeholder="Digite o Preço de Lista" />
                                <span asp-validation-for="PriceCost" class="field-validation-valid text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-4">
                                <label asp-for="DueDate"></label>
                                <input asp-for="DueDate" class="form-control" placeholder="Informe a Data de Vencimento" />
                            </div>
                            <div class="form-group col-md-4">
                                <label asp-for="UnityType"></label>
                                @Html.DropDownList("UnityTypeId", (IEnumerable<SelectListItem>)ViewBag.UnityTypes, null, new { @class = "form-control" })
                                <span asp-validation-for="UnityTypeId" class="field-validation-valid text-danger"></span>
                            </div>
                            <div class="form-group col-md-4">
                                <label asp-for="Unity"></label>
                                <input type="number" asp-for="Unity" class="form-control" placeholder="Digite a Unidade" />
                                <span asp-validation-for="Unity" class="field-validation-valid text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <div style="text-align:end">
                            <a asp-action="Index" class="btn btn-dark mr-2">Retornar</a>
                            <input type="submit" class="btn btn-success" value="Salvar" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

ModulosUsuario/ModulosUsuario/Views/Tools/Index.cshtml
@model IEnumerable<Tools>
@{ ViewData["Title"] = "Ferramentas"; }

<script src="~/js/views/tools.js"></script>

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header d-inline">
                <h3 class="box-title">Gerenciar Ferramentas <a class="float-right" href="/Tools/CreateOrEdit" role="button" title="Criar Ferramenta"><i class="fas fa-plus-square"></i></a></h3>
            </div>
            <div class="box-body">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Status)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Unity)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.DueDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PriceCost)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Status)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Unity)
                                    @Html.DisplayFor(modelItem => item.UnityType.Description)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DueDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PriceCost)
                                </td>
                                <td align="center">
                                    @Html.ActionLink("Editar", "CreateOrEdit", "Tools", new { toolsId = item.ToolsId }, new { @class = "btn btn-sm btn-primary" })
                                    <button deleteToolsId="@item.ToolsId" type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#deleteModal" onclick="toolsController.deleteModalId(this)">
                                        <i class="fas fa-trash-alt"></i> Deletar
                                    </button>
                                    @Html.ActionLink("Log", "Logs", "Tools", new { toolsId = item.ToolsId }, new { @class = "btn btn-sm btn-info" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Confirmar Deleção</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                Tem certeza que deseja deletar esse ferramenta?
            </div>
            <div class="modal-footer">
                <form action="" id="deleteModalAction" asp-antiforgery="true" method="post">
                    <input type="submit" class="btn bg-danger" value="Deletar" />
                </form>
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

ModulosUsuario/ModulosUsuario/Views/Tools/Log.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1>funcionou!</h1>
</body>
</html>

ModulosUsuario/ModulosUsuario/Views/Tools/Logs.cshtml
@model ModulosUsuario.Models.Tools
@{ ViewData["Title"] = "ToolsLog";}

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header d-inline">
                <h3 class="box-title">Logs Ferramentas</h3>
            </div>
            <div class="box-body">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <td>
                                Id da ferramenta
                            </td>
                            <td>
                                Nome da ferramenta
                            </td>
                            <td>
                                Data de saída
                            </td>
                            <td>
                                Data de retorno
                            </td>
                            <td>
                                Retirado por
                            </td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>

                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>